### PR TITLE
Add support for 1.24 and drop support of 1.20

### LINKED ISSUE #176: Support sync command with EKS 1.24
**Describe the solution you'd like**

EKS Kubernetes version 1.24 support was announced, so we should update `kubergrunt eks sync` to support that.

### PR DESCRIPTION
**Pull request by autero1**
## Description

Fixes #176 

This PR updates the `eks sync-core-components` command to add support for k8s version `1.24`. This also removes support for `1.20`, which [has reached end of support in EKS](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar).

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

### CODE REVIEW

**Review by ryehowell-kinsloo — APPROVED** [review]
@autero1 the changes LGTM.

One thing I am wondering though, do you think it makes sense to change [this](https://github.com/gruntwork-io/kubergrunt/blob/main/kubectl/config.go#L114) from `v1beta1` to `v1`? I don't think it's necessary since only `alpha` was dropped, but something we might want to consider (or at least backlog it for the next release bump).

**Review by pras111gw — APPROVED** [review]
tested kubergrunt locally with this change. looks good

**Comment by autero1** [comment]
> One thing I am wondering though, do you think it makes sense to change [this](https://github.com/gruntwork-io/kubergrunt/blob/main/kubectl/config.go#L114) from `v1beta1` to `v1`? I don't think it's necessary since only `alpha` was dropped, but something we might want to consider (or at least backlog it for the next release bump).

I think `v1` was introduced in `1.22`, so changing it would drop support to versions below that. We can keep it as it is, but definitely keep this in mind for future releases.

**Comment by autero1** [comment]
Thanks for the review, merging this in!

**Pull request merged**
