### PR TITLE
Add Support for EKS 1.31

### PR DESCRIPTION
**Pull request by ABHISHEKVALSAN**
Fixes Issue https://github.com/gruntwork-io/kubergrunt/issues/242.

This PR adds support for EKS 1.31

### CODE REVIEW

**Comment by ryehowell** [comment]
Hi @ABHISHEKVALSAN , thanks for submitting this PR. I've kicked off the CI tests.

**Comment by ABHISHEKVALSAN** [comment]
@ryehowell i checked the logs of the failed CI tests but not able to figure out whats wrong. can you help me here?

**Comment by ryehowell** [comment]
Hi @ABHISHEKVALSAN, the tests are failing due to the AddOn versions. The latest versions do not align with what is set in the version table. This is a known issue with the tests. Please update with the following versions:

```go

{coreDNSVersionLookupTable, coreDNSRepoPath, "1.31", "us-east-1", "1.11.3-eksbuild.2"},
{coreDNSVersionLookupTable, coreDNSRepoPath, "1.30", "us-east-1", "1.11.3-eksbuild.2"},
{coreDNSVersionLookupTable, coreDNSRepoPath, "1.29", "us-east-1", "1.11.3-eksbuild.2"},
{coreDNSVersionLookupTable, coreDNSRepoPath, "1.28", "us-east-1", "1.10.1-eksbuild.15"},
{coreDNSVersionLookupTable, coreDNSRepoPath, "1.27", "us-east-1", "1.10.1-eksbuild.15"},
{coreDNSVersionLookupTable, coreDNSRepoPath, "1.26", "us-east-1", "1.9.3-eksbuild.19"},
{coreDNSVersionLookupTable, coreDNSRepoPath, "1.25", "us-east-1", "1.9.3-eksbuild.19"},
{kubeProxyVersionLookupTable, kubeProxyRepoPath, "1.31", "us-east-1", "1.31.0-minimal-eksbuild.6"},
{kubeProxyVersionLookupTable, kubeProxyRepoPath, "1.30", "us-east-1", "1.30.3-minimal-eksbuild.10"},
{kubeProxyVersionLookupTable, kubeProxyRepoPath, "1.29", "us-east-1", "1.29.7-minimal-eksbuild.9"},
{kubeProxyVersionLookupTable, kubeProxyRepoPath, "1.28", "us-east-1", "1.28.12-minimal-eksbuild.11"},
{kubeProxyVersionLookupTable, kubeProxyRepoPath, "1.27", "us-east-1", "1.27.16-minimal-eksbuild.11"},
{kubeProxyVersionLookupTable, kubeProxyRepoPath, "1.26", "us-east-1", "1.26.15-minimal-eksbuild.16"},
{kubeProxyVersionLookupTable, kubeProxyRepoPath, "1.25", "us-east-1", "1.25.16-minimal-eksbuild.19"},

```

**Comment by ryehowell** [comment]
@ABHISHEKVALSAN , re-running the CI tests again.

**Comment by ABHISHEKVALSAN** [comment]
@ryehowell

**Review by ryehowell — APPROVED** [review]
Changes look good. Please note that this will be released as an Alpha release until it is fully tested against the EKS library with EKS `1.31`.

**Pull request merged**
